/**
 * Auto-generated focal points for cropped images.
 * Regenerate: npm run focal-points
 */
export type ImageFocalMethod = "face" | "face-primary" | "subject" | "fallback" | "manual";

export const imageFocalPoints = {
  "/Contact Us Photo.jpg": "41.7% 50.0%",
  "/IMG_0607.jpg": "58.3% 50.0%",
  "/SMH-NBH-NWLUH-SMH-NHS-Website-Logo-Banner-RB.jpg": "50.0% 50.0%",
  "/about main.jpg": "60.4% 50.0%",
  "/favicon/Najib_Daulatzai_Favicon.png": "48.8% 50.0%",
  "/favicon/apple-touch-icon.png": "50.0% 50.0%",
  "/favicon/favicon-16.png": "50.0% 50.0%",
  "/favicon/favicon-192.png": "50.0% 50.0%",
  "/favicon/favicon-32.png": "50.0% 50.0%",
  "/favicon/favicon-512.png": "50.0% 50.0%",
  "/favicon/icon-192.png": "50.0% 50.0%",
  "/favicon/icon-512.png": "50.0% 50.0%",
  "/images/Da Vinci 5 Console lo-res.jpg": "50.0% 50.0%",
  "/images/Najib With Patient.jpg": "35.4% 50.0%",
  "/images/about secondary.jpg": "60.4% 50.0%",
  "/images/about-operating-theatre.png": "66.6% 50.0%",
  "/images/about-section.jpg": "43.7% 50.0%",
  "/images/blog/1.jpg": "52.1% 50.0%",
  "/images/blog/10.jpg": "47.9% 50.0%",
  "/images/blog/11.jpg": "43.8% 50.0%",
  "/images/blog/12.jpg": "50.0% 35.4%",
  "/images/blog/13.jpg": "60.4% 50.0%",
  "/images/blog/14.jpg": "59.8% 50.0%",
  "/images/blog/15.png": "45.8% 50.0%",
  "/images/blog/16.png": "58.3% 50.0%",
  "/images/blog/17.jpg": "50.0% 50.0%",
  "/images/blog/18.jpg": "64.6% 50.0%",
  "/images/blog/19.jpg": "64.6% 50.0%",
  "/images/blog/2.jpg": "43.9% 50.0%",
  "/images/blog/20.jpg": "43.8% 50.0%",
  "/images/blog/3.png": "58.3% 50.0%",
  "/images/blog/4.jpg": "41.7% 50.0%",
  "/images/blog/5.jpg": "63.3% 50.0%",
  "/images/blog/6.jpg": "41.7% 50.0%",
  "/images/blog/7.jpg": "33.4% 50.0%",
  "/images/blog/8.jpg": "56.3% 50.0%",
  "/images/blog/9.jpg": "50.0% 39.6%",
  "/images/book-appointment.png": "44.3% 50.0%",
  "/images/book-cta-patient.jpg": "35.4% 50.0%",
  "/images/contact-page-hero.jpg": "41.7% 50.0%",
  "/images/da-vinci-5-console-lo-res.jpg": "47.4% 50.0%",
  "/images/davinci.jpg": "35.4% 50.0%",
  "/images/davinci/console-front.jpg": "48.0% 50.0%",
  "/images/davinci/da-vinci-5-console-or.jpg": "64.5% 50.0%",
  "/images/davinci/da-vinci-5-console.jpg": "50.0% 50.0%",
  "/images/davinci/da-vinci-5-patient-cart.jpg": "50.0% 50.0%",
  "/images/davinci/da-vinci-5-system.jpg": "34.4% 50.0%",
  "/images/davinci/da-vinci-5-tower.jpg": "50.0% 50.0%",
  "/images/davinci/gen4-system-lineup.jpg": "53.9% 50.0%",
  "/images/davinci/or-staff-patient-cart.jpg": "35.0% 50.0%",
  "/images/davinci/or-staff-vision-cart.jpg": "63.3% 50.0%",
  "/images/davinci/surgeon-at-console.jpg": "54.6% 50.0%",
  "/images/davinci/xi-or-staff.jpg": "37.1% 50.0%",
  "/images/davinci/xi-system-lineup.jpg": "51.6% 50.0%",
  "/images/hero-consultation.jpg": "35.4% 50.0%",
  "/images/images/mobile hero.png": "50.0% 50.0%",
  "/images/images/10.jpg": "47.9% 50.0%",
  "/images/images/12.jpg": "50.0% 35.4%",
  "/images/images/13.jpg": "60.4% 50.0%",
  "/images/images/20.jpg": "43.8% 50.0%",
  "/images/images/Contact Us Photo.jpg": "41.7% 50.0%",
  "/images/images/IMG_0395.jpg": "39.6% 50.0%",
  "/images/images/IMG_0404.jpg": "54.2% 50.0%",
  "/images/images/IMG_0412.jpg": "56.3% 50.0%",
  "/images/images/IMG_0447.jpg": "43.8% 50.0%",
  "/images/images/IMG_0480.jpg": "39.6% 50.0%",
  "/images/images/IMG_0484.jpg": "52.1% 50.0%",
  "/images/images/IMG_0487.jpg": "52.1% 50.0%",
  "/images/images/IMG_0491.jpg": "56.3% 50.0%",
  "/images/images/IMG_0559.jpg": "35.4% 50.0%",
  "/images/images/IMG_0592.jpg": "41.7% 50.0%",
  "/images/images/IMG_0607.jpg": "58.3% 50.0%",
  "/images/images/IMG_0617.jpg": "35.4% 50.0%",
  "/images/images/IMG_0657.jpg": "39.6% 50.0%",
  "/images/images/IMG_0686.jpg": "43.8% 50.0%",
  "/images/images/IMG_0820.jpg": "39.6% 50.0%",
  "/images/images/IMG_0874.jpg": "37.5% 50.0%",
  "/images/images/IMG_0878.jpg": "66.7% 50.0%",
  "/images/images/IMG_0898.jpg": "66.7% 50.0%",
  "/images/images/IMG_0904.jpg": "66.7% 50.0%",
  "/images/images/IMG_0908.jpg": "66.7% 50.0%",
  "/images/images/IMG_0916.jpg": "33.3% 50.0%",
  "/images/images/IMG_0928.jpg": "58.3% 50.0%",
  "/images/images/IMG_0968.jpg": "64.6% 50.0%",
  "/images/images/IMG_0971.jpg": "56.3% 50.0%",
  "/images/images/IMG_1039.jpg": "37.5% 50.0%",
  "/images/images/IMG_1057.jpg": "37.5% 50.0%",
  "/images/images/IMG_1086_edited.png": "50.0% 37.5%",
  "/images/images/Najib D Headshot Arms Folded.png": "43.8% 50.0%",
  "/images/images/Najib With Patient (1).jpg": "35.4% 50.0%",
  "/images/images/__aviva (1).png": "50.0% 50.0%",
  "/images/images/__aviva.png": "50.0% 50.0%",
  "/images/images/__axa.png": "50.0% 50.0%",
  "/images/images/__bupa.png": "50.0% 50.0%",
  "/images/images/__healix.png": "50.0% 50.0%",
  "/images/images/__vitality.png": "50.0% 50.0%",
  "/images/images/__wpa.png": "50.0% 50.0%",
  "/images/images/alliance-for-web-725x500.png": "53.8% 50.0%",
  "/images/procedures-home.jpg": "64.6% 50.0%",
  "/images/procedures-robotic-surgery.png": "66.6% 50.0%",
  "/images/procedures/da-vinci-5-console-or.jpg": "64.6% 50.0%",
  "/images/procedures/doctors-preparing-operation.jpg": "47.9% 50.0%",
  "/images/procedures/doctors-surgical-procedure.jpg": "30.8% 50.0%",
  "/images/procedures/group-surgeons-or-1.jpg": "43.8% 50.0%",
  "/images/procedures/group-surgeons-or.jpg": "43.8% 50.0%",
  "/images/procedures/intuitive-surgeon-console.jpg": "54.6% 50.0%",
  "/images/procedures/intuitive-vision-cart.jpg": "63.3% 50.0%",
  "/images/procedures/nurse-preparing-operation.jpg": "56.2% 50.0%",
  "/images/procedures/serious-operation-darkness.jpg": "41.7% 50.0%",
  "/images/procedures/surgeon-team-or.jpg": "35.4% 50.0%",
  "/images/procedures/surgery-or-1.jpg": "62.5% 50.0%",
  "/images/procedures/surgery-or-2.jpg": "64.6% 50.0%",
  "/images/procedures/surgery-or-3.jpg": "62.5% 50.0%",
  "/images/procedures/surgery-or-4.jpg": "66.7% 50.0%",
  "/images/procedures/surgery-or.jpg": "50.0% 35.4%",
  "/images/procedures/surgery-team-focus.jpg": "43.8% 50.0%",
  "/images/procedures/surgery-theater-1.jpg": "35.4% 50.0%",
  "/images/procedures/surgery-theater-2.jpg": "54.2% 50.0%",
  "/images/procedures/surgery-theater.jpg": "50.0% 47.9%",
  "/images/procedures/surgical-procedure.jpg": "50.0% 42.2%",
  "/st-marks.jpg": "50.0% 50.0%"
} as const;

export const imageFocalMethods = {
  "/Contact Us Photo.jpg": "subject",
  "/IMG_0607.jpg": "subject",
  "/SMH-NBH-NWLUH-SMH-NHS-Website-Logo-Banner-RB.jpg": "subject",
  "/about main.jpg": "subject",
  "/favicon/Najib_Daulatzai_Favicon.png": "subject",
  "/favicon/apple-touch-icon.png": "subject",
  "/favicon/favicon-16.png": "subject",
  "/favicon/favicon-192.png": "subject",
  "/favicon/favicon-32.png": "subject",
  "/favicon/favicon-512.png": "subject",
  "/favicon/icon-192.png": "subject",
  "/favicon/icon-512.png": "subject",
  "/images/Da Vinci 5 Console lo-res.jpg": "subject",
  "/images/Najib With Patient.jpg": "subject",
  "/images/about secondary.jpg": "subject",
  "/images/about-operating-theatre.png": "subject",
  "/images/about-section.jpg": "subject",
  "/images/blog/1.jpg": "subject",
  "/images/blog/10.jpg": "subject",
  "/images/blog/11.jpg": "subject",
  "/images/blog/12.jpg": "subject",
  "/images/blog/13.jpg": "subject",
  "/images/blog/14.jpg": "subject",
  "/images/blog/15.png": "subject",
  "/images/blog/16.png": "subject",
  "/images/blog/17.jpg": "subject",
  "/images/blog/18.jpg": "subject",
  "/images/blog/19.jpg": "subject",
  "/images/blog/2.jpg": "subject",
  "/images/blog/20.jpg": "subject",
  "/images/blog/3.png": "subject",
  "/images/blog/4.jpg": "subject",
  "/images/blog/5.jpg": "subject",
  "/images/blog/6.jpg": "subject",
  "/images/blog/7.jpg": "subject",
  "/images/blog/8.jpg": "subject",
  "/images/blog/9.jpg": "subject",
  "/images/book-appointment.png": "subject",
  "/images/book-cta-patient.jpg": "subject",
  "/images/contact-page-hero.jpg": "subject",
  "/images/da-vinci-5-console-lo-res.jpg": "subject",
  "/images/davinci.jpg": "subject",
  "/images/davinci/console-front.jpg": "subject",
  "/images/davinci/da-vinci-5-console-or.jpg": "subject",
  "/images/davinci/da-vinci-5-console.jpg": "subject",
  "/images/davinci/da-vinci-5-patient-cart.jpg": "subject",
  "/images/davinci/da-vinci-5-system.jpg": "subject",
  "/images/davinci/da-vinci-5-tower.jpg": "subject",
  "/images/davinci/gen4-system-lineup.jpg": "subject",
  "/images/davinci/or-staff-patient-cart.jpg": "subject",
  "/images/davinci/or-staff-vision-cart.jpg": "subject",
  "/images/davinci/surgeon-at-console.jpg": "subject",
  "/images/davinci/xi-or-staff.jpg": "subject",
  "/images/davinci/xi-system-lineup.jpg": "subject",
  "/images/hero-consultation.jpg": "subject",
  "/images/images/10.jpg": "subject",
  "/images/images/12.jpg": "subject",
  "/images/images/13.jpg": "subject",
  "/images/images/20.jpg": "subject",
  "/images/images/Contact Us Photo.jpg": "subject",
  "/images/images/IMG_0395.jpg": "subject",
  "/images/images/IMG_0404.jpg": "subject",
  "/images/images/IMG_0412.jpg": "subject",
  "/images/images/IMG_0447.jpg": "subject",
  "/images/images/IMG_0480.jpg": "subject",
  "/images/images/IMG_0484.jpg": "subject",
  "/images/images/IMG_0487.jpg": "subject",
  "/images/images/IMG_0491.jpg": "subject",
  "/images/images/IMG_0559.jpg": "subject",
  "/images/images/IMG_0592.jpg": "subject",
  "/images/images/IMG_0607.jpg": "subject",
  "/images/images/IMG_0617.jpg": "subject",
  "/images/images/IMG_0657.jpg": "subject",
  "/images/images/IMG_0686.jpg": "subject",
  "/images/images/IMG_0820.jpg": "subject",
  "/images/images/IMG_0874.jpg": "subject",
  "/images/images/IMG_0878.jpg": "subject",
  "/images/images/IMG_0898.jpg": "subject",
  "/images/images/IMG_0904.jpg": "subject",
  "/images/images/IMG_0908.jpg": "subject",
  "/images/images/IMG_0916.jpg": "subject",
  "/images/images/IMG_0928.jpg": "subject",
  "/images/images/IMG_0968.jpg": "subject",
  "/images/images/IMG_0971.jpg": "subject",
  "/images/images/IMG_1039.jpg": "subject",
  "/images/images/IMG_1057.jpg": "subject",
  "/images/images/IMG_1086_edited.png": "subject",
  "/images/images/Najib D Headshot Arms Folded.png": "subject",
  "/images/images/Najib With Patient (1).jpg": "subject",
  "/images/images/__aviva (1).png": "subject",
  "/images/images/__aviva.png": "subject",
  "/images/images/__axa.png": "subject",
  "/images/images/__bupa.png": "subject",
  "/images/images/__healix.png": "subject",
  "/images/images/__vitality.png": "subject",
  "/images/images/__wpa.png": "subject",
  "/images/images/alliance-for-web-725x500.png": "subject",
  "/images/procedures-home.jpg": "subject",
  "/images/procedures-robotic-surgery.png": "subject",
  "/images/procedures/da-vinci-5-console-or.jpg": "subject",
  "/images/procedures/doctors-preparing-operation.jpg": "subject",
  "/images/procedures/doctors-surgical-procedure.jpg": "subject",
  "/images/procedures/group-surgeons-or-1.jpg": "subject",
  "/images/procedures/group-surgeons-or.jpg": "subject",
  "/images/procedures/intuitive-surgeon-console.jpg": "subject",
  "/images/procedures/intuitive-vision-cart.jpg": "subject",
  "/images/procedures/nurse-preparing-operation.jpg": "subject",
  "/images/procedures/serious-operation-darkness.jpg": "subject",
  "/images/procedures/surgeon-team-or.jpg": "subject",
  "/images/procedures/surgery-or-1.jpg": "subject",
  "/images/procedures/surgery-or-2.jpg": "subject",
  "/images/procedures/surgery-or-3.jpg": "subject",
  "/images/procedures/surgery-or-4.jpg": "subject",
  "/images/procedures/surgery-or.jpg": "subject",
  "/images/procedures/surgery-team-focus.jpg": "subject",
  "/images/procedures/surgery-theater-1.jpg": "subject",
  "/images/procedures/surgery-theater-2.jpg": "subject",
  "/images/procedures/surgery-theater.jpg": "subject",
  "/images/procedures/surgical-procedure.jpg": "subject",
  "/st-marks.jpg": "subject"
} as const;

export type ImageFocalPath = keyof typeof imageFocalPoints;
